name: muscle_recipe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  google_generative_ai: ^0.4.2
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:        # ← 新規追加
    - .env       # ← 新規追加